package com.glt.magikoly.constants;

import static com.glt.magikoly.constants.PackageName.PACKAGE_NAME;

/**
 * 广播类型
 */
public interface ICustomAction {
    String ACTION_KILL_SELF = PACKAGE_NAME + ".intent.ACTION_KILL_SELF";
    String ACTION_UPLOAD_BASIC_STATISTIC = PACKAGE_NAME + ".intent.ACTION_UPLOAD_BASIC_STATISTIC";
    /**
     * abtest服务器请求，同步子进程数据
     */
    String  ACTION_CONFIG_BEAN_CHANGE = PACKAGE_NAME + ".intent.ACTION_CONFIG_CHANGE";
    String ACTION_PURCHASE_FUNCTION_CONFIG = PACKAGE_NAME + ".intent.ACTION_PURCHASE_FUNCTION_CONFIG";
    String ACTION_AGING_SHUTTER_CONFIG = PACKAGE_NAME + ".intent.ACTION_AGING_SHUTTER_CONFIG";
    String ACTION_DISCOVERY_SEARCH_CONFIG = PACKAGE_NAME + ".intent.ACTION_DISCOVERY_SEARCH_CONFIG";
    String ACTION_DISCOVERY_HOTWORD_CONFIG = PACKAGE_NAME + ".intent.ACTION_DISCOVERY_HOTWORD_CONFIG";
    String ACTION_INNER_AD_CONFIG = PACKAGE_NAME + ".intent.ACTION_INNER_AD_CONFIG";

    String ACTION_ART_FILTER_CONFIG = PACKAGE_NAME + ".intent.ACTION_ART_FILTER_CONFIG";
    String ACTION_MAIN_BANNER_CONFIG = PACKAGE_NAME + ".intent.ACTION_MAIN_BANNER_CONFIG";
    String ACTION_ANIMAL_CONFIG = PACKAGE_NAME + ".intent.ACTION_ANIMAL_CONFIG";
}
